import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "./utils/fonts/roboto";
import CustomSnackbar from "./components/common/custom-snakebar";
import { SnackBarProvider } from "./utils/contexts/snackebar-context";
import ThemeProvider from "./utils/contexts/theme-provider";

export const metadata: Metadata = {
  title: "POWER SOFT APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased w-full h-dvh flex justify-center items-center`}
      >
        <ThemeProvider>
          <SnackBarProvider>
            <CustomSnackbar />
            {children}
          </SnackBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
